database_path: "quantme.db"
collect_mode: "always" # "always" or "focus"
collection_interval_seconds: 2
keypress_collection: false
pomodoro:
  focus_minutes: 25
  short_break_minutes: 5
  long_break_minutes: 15
  long_break_interval: 4 # Long break after this many focus sessions
